### ISSUE TITLE
"'automake-1.14' is missing on your system."

### ISSUE THREAD

**Issue by borellim** [hyperrealm/libconfig#22]
Hello. I get this error when I run 'make'. The 'configure' phase seems to be successful.
I don't have automake 1.14 installed on this machine, but I don't think I should. I have 1.13, but even after uninstalling it nothing changes.
An even weirder thing is that on another machine, where only automake 1.11 is installed, this error is not thrown and the compilation succeeds.

Here is the full error message:
```
[marco@localhost source]$ make
 cd . && /bin/sh /home/marco/Scaricati/libconfig-1.5/source/aux-build/missing automake-1.14 --gnu
/home/marco/Scaricati/libconfig-1.5/source/aux-build/missing: line 81: automake-1.14: command not found
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile.in] Errore 1
```

Thank you.

**Comment by hyperrealm** [comment]
Should be fixed now as I added all the *.in files to the repo.

**Comment by franklixuefei** [comment]
Hi,

I also encountered the similar issue after I git cloned the repo.
after I <code>./configure</code>, when I <code>make</code>, the following appears:
<pre>
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/frank/Documents/libconfig/aux-build/missing aclocal-1.14 -I m4
/home/frank/Documents/libconfig/aux-build/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:399: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
</pre>

But if I just use the tarball on your website, everything is fine.

Thanks!

Frank

**Comment by 7profy** [comment]
Hi.
I suppose that not fixed yet!
Make fails as described above when l load library `git clone https://github.com/hyperrealm/libconfig.git`
And make fails if I manually load and unzip:
 ```
make  all-recursive
make[1]: Entering directory '/home/pi/libconfig'
Making all in lib
make[2]: Entering directory '/home/pi/libconfig/lib'
make  all-am
make[3]: Entering directory '/home/pi/libconfig/lib'
  CC       libconfig_la-libconfig.lo
  CC       libconfig_la-scanner.lo
scanner.l: In function 'libconfig_yylex':
scanner.l:137:53: warning: passing argument 3 of 'scanctx_push_include' from incompatible pointer type
                     char c[2] = { (char)(strtol(yytext + 2, NULL, 16) & 0xFF),
                                                     ^
In file included from scanner.l:46:0:
scanctx.h:66:14: note: expected 'const char *' but argument is of type 'const char **'
 extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
              ^
scanner.l:135:32: error: too few arguments to function 'scanctx_push_include'
 <STRING>\\\"      { scanctx_append_string(yyextra, "\""); }
                                ^
In file included from scanner.l:46:0:
scanctx.h:66:14: note: declared here
 extern FILE *scanctx_push_include(struct scan_context *ctx, void *prev_buffer,
              ^
Makefile:614: recipe for target 'libconfig_la-scanner.lo' failed
make[3]: *** [libconfig_la-scanner.lo] Error 1
make[3]: Leaving directory '/home/pi/libconfig/lib'
Makefile:445: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pi/libconfig/lib'
Makefile:435: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/libconfig'
Makefile:364: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by elderpinzon** [comment]
Unfortunately seeing the same issue on multiple machines with aclocal 1.13.4 with the master branch, as well as the 1.5 and 1.6 tags. Downloading the 1.5 version from http://www.hyperrealm.com/libconfig/libconfig-1.5.tar.gz works.

I'm trying to use this repo as a submodule for my own so I would like to get it to compile.

**Comment by borellim** [comment]
@elderpinzon: I agree, git does not preserve timestamps and this triggers automake to run again.
Besides not using git at all, I found another workaround (taken from [here](http://stackoverflow.com/a/5745366)):
```
make AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:
make install AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:
```
This should prevent the automake/autoconf executables from running, and it seems to work great.

I'm not sure if @7profy's error is due to this, though.

**Comment by elderpinzon** [comment]
Thank you very much @borellim! I think that this trick will do the job for now. Since I am using a tagged version, i.e., there shouldn't be any mods to the source code and config files, I presume this should be safe.
